from __future__ import annotations

MENU_TO_ACTION = {
    "Genel Bakış": "dashboard.view",
    "Satış": "sales.view",
    "Restoran Yönetimi": "restaurant.view",
    "Personel Yönetimi": "personnel.view",
    "Puantaj": "attendance.view",
    "Satın Alma": "purchase.view",
    "Kesinti Yönetimi": "deduction.view",
    "Aylık Hakediş": "payroll.view",
    "Raporlar ve Karlılık": "reporting.view",
    "Sistem Kayıtları": "audit.view",
    "Güncellemeler ve Duyurular": "announcements.view",
}


ACTION_LABELS = {
    "dashboard.view": "Genel Bakış ekranını görüntüleme",
    "sales.view": "satış ekranını görüntüleme",
    "sales.create": "satış talebi oluşturma",
    "sales.update": "satış talebi güncelleme",
    "sales.delete": "satış talebi silme",
    "restaurant.view": "Restoran ekranını görüntüleme",
    "restaurant.create": "restoran oluşturma",
    "restaurant.update": "restoran güncelleme",
    "restaurant.status_change": "restoran aktifleştirme/pasife alma",
    "restaurant.delete": "restoran silme",
    "personnel.view": "personel ekranını görüntüleme",
    "personnel.list": "personel listesini görüntüleme",
    "personnel.create": "personel oluşturma",
    "personnel.update": "personel güncelleme",
    "personnel.status_change": "personel aktifleştirme/pasife alma",
    "personnel.delete": "personel silme",
    "personnel.plate": "plaka ve motor alanını görüntüleme",
    "attendance.view": "puantaj ekranını görüntüleme",
    "attendance.create": "günlük puantaj oluşturma",
    "attendance.update": "günlük puantaj güncelleme",
    "attendance.delete": "günlük puantaj silme",
    "attendance.bulk_create": "toplu puantaj kaydetme",
    "attendance.bulk_delete": "filtrelenmiş günlük puantaj toplu silme",
    "purchase.view": "satın alma ekranını görüntüleme",
    "purchase.create": "satın alma oluşturma",
    "purchase.update": "satın alma güncelleme",
    "purchase.delete": "satın alma silme",
    "deduction.view": "kesinti ekranını görüntüleme",
    "deduction.create": "kesinti oluşturma",
    "deduction.update": "kesinti güncelleme",
    "deduction.delete": "kesinti silme",
    "deduction.bulk_delete": "toplu kesinti silme",
    "equipment.view": "ekipman ekranını görüntüleme",
    "equipment.create": "ekipman hareketi oluşturma",
    "equipment.bulk_update": "toplu ekipman güncelleme",
    "equipment.bulk_delete": "toplu ekipman silme",
    "equipment.box_return": "box geri alım kaydetme",
    "payroll.view": "aylık hakediş ekranını görüntüleme",
    "reporting.view": "raporlar ekranını görüntüleme",
    "audit.view": "sistem kayıtlarını görüntüleme",
    "announcements.view": "duyuru ekranını görüntüleme",
    "backup.manage": "veri yedekleme ve aktarma işlemleri",
}


ROLE_ACTIONS = {
    "admin": set(ACTION_LABELS.keys()),
    "sef": {
        "sales.view",
        "sales.create",
        "sales.update",
        "personnel.view",
        "personnel.list",
        "personnel.create",
        "personnel.update",
        "personnel.status_change",
        "personnel.plate",
        "attendance.view",
        "attendance.create",
        "attendance.update",
        "attendance.delete",
        "attendance.bulk_create",
        "attendance.bulk_delete",
        "deduction.view",
        "deduction.create",
        "deduction.update",
        "deduction.delete",
        "deduction.bulk_delete",
        "announcements.view",
    },
    "mobile_ops": {
        "personnel.view",
        "personnel.create",
        "attendance.view",
        "attendance.create",
        "attendance.update",
    },
}
